### PR TITLE
Expose Project Importer Config Through Env Vars

### PR DESCRIPTION
**Pull request by zicklag**
Allows enabling the Taiga project importers for GitHub, Trello, JIRA, and Asana.

### CODE REVIEW

**Comment by zicklag** [comment]
This should work now. I've only tested the GitHub importer, though.

**Comment by blackandred** [comment]
I was thinking why I cannot see the Trello importer :thinking: 
So, we need to test it with all importers.

Last time we didn't have tested normal login when introduced LDAP. In result people already with a session remembered were logged in, but new sessions could not be created :stuck_out_tongue:

**Comment by blackandred** [comment]
Thank you for this PR, many people will use this feature I guess, and I personally would use the Trello import :smiley:

**Comment by zicklag** [comment]
> Last time we didn't have tested normal login when introduced LDAP. In result people already with a session remembered were logged in, but new sessions could not be created :stuck_out_tongue:

Oops. :stuck_out_tongue_winking_eye: 

---

@blackandred Are you good testing the Trello importer?

I don't have any JIRA or Asana instances to test on either.

If nobody can test those, then maybe we could just say that those importers are untested in the README?

**Comment by blackandred** [comment]
When I will have a moment I will test the Trello importer.

**Comment by blackandred** [comment]
I think - we can test importers we are able to test. And the second criteria for merging should be that the application will be working at all - logging in, and basic things like creating a task on board, mail with a password recovery, the admin panel access.

**Comment by blackandred** [comment]
Personlly I can test Trello, Taiga and Github. Maybe JIRA, I'm not sure.

**Comment by zicklag** [comment]
That makes sense to me. If it doesn't break anything else, we should be good. I can run the updated version on my production instance. I use LDAP to login. If you could test the version with local auth, then that should be good enough I would think.

**Comment by blackandred** [comment]
Sure, I will test in few days I think. Currently I have too much other work
to do :/

**Comment by blackandred** [comment]
Hi, sorry for late response. I was sick for 2 weeks and for other time had a lot to do. Merging now.

**Comment by zicklag** [comment]
Hey, no problem. 

We should update the README with the latest environment variables now, right? Is that a part of CI or do we do that manually?

**Comment by blackandred** [comment]
It's updated by a git hook (see README). When you add something to ENV,
then on git pre-commit the README is generated. You can also generate the
README from Makefile task.

**Comment by blackandred** [comment]
It seems it its already added.

```
# Enable the GitHub project importer
- TAIGA_IMPORTER_GITHUB_ENABLED # (default: "false")

# GitHub importer client ID
- TAIGA_IMPORTER_GITHUB_CLIENT_ID # (default: "")

# GitHub importer client secret
- TAIGA_IMPORTER_GITHUB_CLIENT_SECRET # (default: "")

# Enable the Trello project importer
- TAIGA_IMPORTER_TRELLO_ENABLED # (default: "false")

# Trello importer api key
- TAIGA_IMPORTER_TRELLO_API_KEY # (default: "")

# Trello importer secret key
- TAIGA_IMPORTER_TRELLO_SECRET_KEY # (default: "")

# Enable the JIRA project importer
- TAIGA_IMPORTER_JIRA_ENABLED # (default: "false")

# JIRA importer consumer key
- TAIGA_IMPORTER_JIRA_CONSUMER_KEY # (default: "")

# JIRA importer cert
- TAIGA_IMPORTER_JIRA_CERT # (default: "")

# JIRA importer public cert
- TAIGA_IMPORTER_JIRA_PUB_CERT # (default: "")

# Enable the Asana project importer
- TAIGA_IMPORTER_ASANA_ENABLED # (default: "false")

# Override callback URL for Asana importer. Will be automatically set based on Taiga URL if left blank.
- TAIGA_IMPORTER_ASANA_CALLBACK_URL # (default: "")

# Asana importer app ID
- TAIGA_IMPORTER_ASANA_APP_ID # (default: "")

# Asana importer app secret
- TAIGA_IMPORTER_ASANA_APP_SECRET # (default: "")
```

**Comment by zicklag** [comment]
Oh, sorry, I don't know how I missed that. Git hooks, are a good idea. I hadn't thought of that.

**Comment by blackandred** [comment]
# :slightly_smiling_face:

**Pull request merged**
