### PR TITLE
Fix nginx emerg when TAIGA_REDIRECT_TO_SSL=true

### PR DESCRIPTION
**Pull request by NokiDev**
Was experiencing an issue when using TAIGA_REDIRECT_TO_SSL

Nginx was using two default_server directives leading to an horrible nginx emerg
`nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/nginx.conf:34`

I fixed it but not sure how it was intended to work, should we provide a volume mapping for passing certificates ? 

Cheers

### CODE REVIEW

**Comment by zicklag** [comment]
I think we decided that we didn't want to do SSL termination *inside* the container in favor of doing it in a reverse proxy that is outside of the container. Is that right @blackandred?

**Comment by blackandred** [comment]
Hi, thank you @NokiDev for the contribution.

Unfortunately this looks like a part of functionality we wanted to delete from container as the container was forked from other project. As part of https://github.com/riotkit-org/docker-taiga/issues/16 I attempted to remove SSL functionality from container, as the best way to use SSL is to have a reverse proxy and maintaining such SSL support is painful and difficult to test.

**Comment by NokiDev** [comment]
Oh, okay that makes much more sense thanks for your reply.
It's fine to me, I'm already using a reverse proxy for managing my certificates.

Since you seems to have done the necessary in your commit [953404d38a24e8bf0e7ba179a0bf68751c9e1f5d](https://github.com/riotkit-org/docker-taiga/commit/953404d38a24e8bf0e7ba179a0bf68751c9e1f5d)
I will close this PR

**Comment by blackandred** [comment]
Thanks :wink:

**Pull request closed without merging**
