### PR TITLE
add support for webhooks

### LINKED ISSUE #33: Add support for webhooks
Webhooks are disabled by default. It requires to be enabled in `local.py`: https://github.com/taigaio/taiga-back/issues/878

Is it possible to add an environment variable to be able to enable the support of webhooks?

### PR DESCRIPTION
**Pull request by unixfox**
This fixes #33 

Let me know if you want me to modify some changes about this PR.

### CODE REVIEW

**Review by blackandred — COMMENTED** [review]
Looks ok. Could you please update the README.md.j2?

**Comment by unixfox** [comment]
Sure but what do you want me to add? I don't really understand what's needed relating to this new env to add to the `README.md.j2` file.

**Comment by blackandred** [comment]
Ok, my bad, it's a project developed when needed, forgot how it works - I
will merge it, then we can release a testing version.

**Comment by blackandred** [comment]
Ok, created a pre-release https://github.com/riotkit-org/docker-taiga/releases/tag/1.3-RC1
After CI will pass there will be tagged RC-1 versions on https://quay.io/repository/riotkit/taiga?tag=latest&tab=tags

**Comment by unixfox** [comment]
Thank you :).

I just tested the image and it works perfectly on my setup.

**Comment by blackandred** [comment]
Cool :) When I will have some free time I will also test it and release as
stable then :)

**Pull request merged**
