### PR TITLE
WIP: Your issues aren't enabled and I want to communicate with you.

### PR DESCRIPTION
**Pull request by Leopere**
This repository is the only one that's ever managed to get me a working taiga docker compose going however is there any chance where I won't require Make to get the compose functional?

### CODE REVIEW

**Comment by blackandred** [comment]
Hi, make is a kind of automation, but you don't have to use it.

When you type `make start` you have a command that you can use without make.

```
➜  docker-taiga git:(master) ✗ make start
test -f .env || cp .env.dist .env
sudo bash -c "VERSION=4.2.7 docker-compose -p taiga up"
```

So, just take the `sudo bash -c "VERSION=4.2.7 docker-compose -p taiga up"` and it should work without make.

**Comment by blackandred** [comment]
By the way, sorry - I didn't notice that a fork have disabled the issues tab by default.

**Comment by blackandred** [comment]
I can share our production config:

```
version: "2.3"

volumes:
    postgres:
    media:

services:
    postgres:
        image: postgres:11.3-alpine
        environment:
            - POSTGRES_USER=${TAIGA_DB_USER}
            - POSTGRES_DB=${TAIGA_DB}
            - POSTGRES_PASSWORD=${TAIGA_DB_PASSWD}
        volumes:
            - postgres:/var/lib/postgresql/data

    taiga:
        image: quay.io/riotkit/taiga:4.2.5
        links:
            - postgres
        volumes:
            - media:/usr/src/taiga-back/media
        environment:
            - VERSION=4.2.5
            - TAIGA_HOSTNAME=your-domain-there
            - TAIGA_SCHEME=https
            - TAIGA_SECRET_KEY=${TAIGA_SECRET_KEY}
            - TAIGA_DEFAULT_LOCALE=en
            - TAIGA_ENABLE_SSL=false
            - TAIGA_REDIRECT_TO_SSL=false

            - TAIGA_DB_NAME=${TAIGA_DB}
            - TAIGA_DB_HOST=postgres
            - TAIGA_DB_USER=${TAIGA_DB_USER}
            - TAIGA_DB_PASSWORD=${TAIGA_DB_PASSWD}

            - TAIGA_ENABLE_EMAIL=true
            - TAIGA_EMAIL_FROM=no-reply@your-domain-org
            - TAIGA_EMAIL_USE_TLS=false
            - TAIGA_EMAIL_HOST=${SMARTHOST_ADDRESS}
            - TAIGA_EMAIL_PORT=${SMARTHOST_PORT}
            - TAIGA_EMAIL_USER=${SMARTHOST_USER}
            - TAIGA_EMAIL_PASS=${SMARTHOST_PASSWORD}

           # events are not supported yet
            - TAIGA_ENABLE_EVENTS=false
            #- TAIGA_EVENTS_HOST=taiga_events
            #- TAIGA_BROKER_URL=amqp://guest:guest@taiga_rabbit:5672
            #- TAIGA_REDIS_URL=redis://redis:6379/5
```

**Comment by Leopere** [comment]
I was glancing over this the other day and wanted it working pretty badly.  The biggest thing I really want is for this damn app to fit behind my Traefik Reverse Proxy and this has proven to be an absolute kludge.  

It's almost as if Taiga doesn't actually want you to use their FOSS code.

**Comment by blackandred** [comment]
We use it behind NGINX (connected via nginx-proxy), it works very fine. Should work in my opinion with Traefik without any issue.

**Comment by blackandred** [comment]
Closing the MR, you can create a new issue if you need anything more.

**Pull request closed without merging**
